name: SBT CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        fetch-depth: 0
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: get previous version
      run: echo "PREVIOUS_RELEASE_TAG=`git describe --abbrev=0`" >> $GITHUB_ENV
    - name: print local var
      run: echo PREVIOUS_RELEASE_TAG = ${PREVIOUS_RELEASE_TAG}
    - name: prepare release
      run: ./.github/script.sh
